services:
  seawave-db:
    image: mariadb:11.4
    container_name: seawave-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: seawave
      MYSQL_USER: ${MARIADB_API_USER}
      MYSQL_PASSWORD: ${MARIADB_API_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d:ro
      - seawave-db-data:/var/lib/mysql

  seawave-api:
    image: seawave-api
    build:
      context: .
      dockerfile: SeawaveAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:8081;http://+:8080;"
      ASPNETCORE_Kestrel__Endpoints__HttpsEndpoint__Url: "https://+:8081"
      ASPNETCORE_Kestrel__Endpoints__HttpsEndpoint__Certificate__Path: "${SEAWAVE_SERVER_CERTIFICATE}"
      ASPNETCORE_Kestrel__Endpoints__HttpsEndpoint__Certificate__KeyPath: "${SEAWAVE_SERVER_PRIVATE_KEY}"
      ConnectionStrings__DefaultConnection: "Server=seawave-db;Port=3307;Database=seawave;Uid=${MARIADB_API_USER};Pwd=${MARIADB_API_PASSWORD};AllowZeroDateTime=True;TreatTinyAsBoolean=True;DateTimeKind=Utc;"
    volumes:
      - ./certs:/custom-certs:ro
    depends_on:
      - seawave-db

volumes:
  seawave-db-data: